### ISSUE TITLE
Feature Flag Architecture: Core Tests Behind Optional Benchmark Flag

### ISSUE THREAD

**Issue by HikaruEgashira** [HikaruEgashira/parsentry#125]
## Issue Summary

Critical feature flag misorganization where core analyzer functionality tests require the optional `benchmark` feature flag, resulting in incomplete test coverage in default CI/CD pipelines and poor developer experience.

#### 1. Core Functionality Incorrectly Gated
**Issue**: Essential analyzer tests require `benchmark` feature flag
```toml
[[test]]
name = "analyzer_test"
required-features = ["benchmark"]  # ← CRITICAL: Core functionality

[[test]]
name = "analyzer_unit_test"  
required-features = ["benchmark"]  # ← Should be unit tests, not benchmark
```

#### 2. Test Coverage Impact
**Current State**:
```bash
cargo test                     # 134 tests (62% coverage)
cargo test --features benchmark # 214 tests (100% coverage)
```

**Missing Core Tests in Default Run**:
- `analyzer_test.rs` - Core analyzer functionality with snapshot tests
- `analyzer_unit_test.rs` - Unit tests for analyzer logic (should not require API)
- `prompt_accuracy_unit_test.rs` - Unit tests for prompt handling

#### 3. Developer Experience Issues
- Default `cargo test` misses 37% of test suite (80 tests)
- Core analyzer functionality untested in standard workflow
- New developers must learn non-standard test execution patterns
- CI/CD pipelines miss critical functionality validation

#### Current Configuration Issues
```toml
[features]
default = []
snapshot-test = []
benchmark = []

# 10 test files incorrectly require "benchmark" feature
# Mix of true benchmarks and core functionality tests
```

#### Misclassified Tests

**Should NOT Require benchmark Feature**:
- `analyzer_unit_test.rs` - Unit tests with mock logic
- `prompt_accuracy_unit_test.rs` - Unit tests for prompt handling  
- Any test that can run without external API calls

**Correctly Classified**:
- `performance_benchmark_test.rs` - True performance benchmarking
- `real_world_benchmark_test.rs` - External benchmark validation
- `external_benchmark_integration_test.rs` - Integration with benchmark suites

### 1. CI/CD Pipeline Deficiency
**Current CI Configuration**: 
```yaml
- name: Run tests
  run: cargo test --verbose  # Missing 37% of functionality
```

**Missing Validation**:
- Core analyzer logic not tested
- LLM integration not validated  
- Snapshot consistency not checked

### 2. Development Workflow Problems
- Contributors miss test failures in core functionality
- False confidence from incomplete test runs
- Harder to identify breaking changes during development

### 3. Test Organization Issues
- No clear separation between unit tests and integration tests
- Feature flags used inconsistently for categorization
- Mixing performance tests with functional tests

#### New Feature Structure
```toml
[features]
default = ["core-tests"]
core-tests = []              # Essential functionality tests (always run)
api-tests = []               # Tests requiring LLM API calls
benchmark = []               # Performance and external benchmarks  
snapshot-test = []           # Snapshot testing capability
all-tests = ["core-tests", "api-tests", "benchmark", "snapshot-test"]
```

#### Test Reclassification
```toml
# Core unit tests (no feature requirement)
[[test]]
name = "analyzer_unit_test"  # Remove required-features
path = "tests/analyzer_unit_test.rs"

[[test]]
name = "prompt_accuracy_unit_test"  # Remove required-features  
path = "tests/prompt_accuracy_unit_test.rs"

# API integration tests
[[test]]
name = "analyzer_test"
path = "tests/analyzer_test.rs"
required-features = ["api-tests", "snapshot-test"]

# True benchmarks
[[test]]
name = "performance_benchmark_test"
path = "tests/performance_benchmark_test.rs"
required-features = ["benchmark"]
```

### Option 2: Enhanced CI Strategy
```yaml
# Multi-tier testing approach
- name: Run core tests
  run: cargo test --features core-tests

- name: Run API tests (if keys available)
  run: cargo test --features api-tests
  if: env.OPENAI_API_KEY \!= ''

- name: Run benchmarks (scheduled)
  run: cargo test --features benchmark
  if: github.event_name == 'schedule'
```

### Phase 1: Immediate Fixes (1 week)
1. **Remove benchmark requirement** from true unit tests
   ```toml
   # analyzer_unit_test.rs - Remove required-features line
   # prompt_accuracy_unit_test.rs - Remove required-features line
   ```

2. **Validate unit tests work without API calls**
   - Ensure mock implementations are complete
   - Remove any accidental API dependencies

### Phase 2: Feature Flag Restructure (2 weeks)  
1. **Implement new feature flag structure**
2. **Reclassify tests appropriately**
3. **Update CI/CD configuration**
4. **Add feature flag documentation**

### Phase 3: Validation (1 week)
1. **Test all feature flag combinations**
2. **Validate CI pipeline improvements**  
3. **Update developer documentation**
4. **Create feature flag governance guidelines**

### Developer Experience Improvements
- **94% test coverage** in default execution (vs 62% currently)
- **Fast feedback loop** with core tests always running
- **Clear test categorization** for different purposes
- **Easier onboarding** for new contributors

### CI/CD Pipeline Improvements  
- **Complete functionality validation** in default runs
- **Efficient resource usage** with tiered testing approach
- **Better failure attribution** (core vs integration vs performance)
- **Flexible testing strategy** for different environments

### Architecture Benefits
- **Logical test organization** by purpose and requirements
- **Clear separation of concerns** in test architecture
- **Improved maintainability** through consistent categorization
- **Better scalability** for adding new test types

### Phase 1 (Immediate)
- [ ] Remove `benchmark` requirement from `analyzer_unit_test.rs`
- [ ] Remove `benchmark` requirement from `prompt_accuracy_unit_test.rs`  
- [ ] Validate these tests run successfully without API calls
- [ ] Verify default `cargo test` includes core analyzer functionality

### Phase 2 (Architecture)
- [ ] Implement new feature flag structure (`core-tests`, `api-tests`, `benchmark`)
- [ ] Reclassify all test files appropriately
- [ ] Update CI/CD pipeline to use tiered testing approach
- [ ] Document feature flag strategy and test categorization

### Phase 3 (Quality)
- [ ] Test all feature flag combinations work correctly
- [ ] Achieve >90% test coverage in default `cargo test` run
- [ ] Create feature flag governance documentation
- [ ] Validate improved developer experience

### Cargo.toml Changes
- Feature flag structure reorganization
- Test classification updates
- New feature dependencies

### CI/CD Configuration
- `.github/workflows/` - Enhanced testing strategy
- Multiple test execution tiers

### Documentation
- README.md - Updated testing instructions
- Developer documentation - Feature flag guidance

### Implementation Risk: **LOW**
- Well-understood changes to build configuration
- Incremental migration possible
- Easy to revert if issues occur

### Performance Risk: **POSITIVE**
- Faster default test execution
- More efficient CI resource usage
- Better parallelization opportunities

## Priority Justification

**P1 - High Priority**: This issue directly impacts developer productivity and CI/CD effectiveness. Core functionality should always be tested by default. The current state creates false confidence and makes it harder to catch regressions in essential features.

**Impact**: Developer experience, CI effectiveness, test coverage quality
**Effort**: Low (configuration changes)  
**Risk**: Low (improving test organization)
**Value**: High (immediate workflow improvement)

### Analysis Subtasks
- [ ] **FF-A1**: Audit all test files and their current feature flag requirements
- [ ] **FF-A2**: Identify true unit tests vs integration tests vs benchmarks
- [ ] **FF-A3**: Analyze CI/CD pipeline test coverage gaps
- [ ] **FF-A4**: Map current feature flag usage patterns across the codebase

### Implementation Subtasks
- [ ] **FF-I1**: Remove benchmark requirement from true unit tests
- [ ] **FF-I2**: Implement new feature flag structure (core-tests, api-tests, benchmark)
- [ ] **FF-I3**: Reclassify all test files with appropriate feature requirements
- [ ] **FF-I4**: Update CI/CD configuration for tiered testing approach

### Documentation Subtasks
- [ ] **FF-D1**: Update README.md with new testing instructions and feature flags
- [ ] **FF-D2**: Create feature flag governance documentation
- [ ] **FF-D3**: Document test categorization strategy for developers
- [ ] **FF-D4**: Update developer onboarding docs with correct test commands

### Validation Subtasks
- [ ] **FF-V1**: Test all feature flag combinations work correctly
- [ ] **FF-V2**: Validate >90% test coverage in default cargo test run
- [ ] **FF-V3**: Verify improved CI pipeline efficiency and coverage
- [ ] **FF-V4**: Confirm improved developer experience with faster feedback
