### ISSUE TITLE
[FEATURE] Configuration File Support (TOML)

### ISSUE THREAD

**Issue by HikaruEgashira** [HikaruEgashira/parsentry#138]
## Feature Summary
Parsentryの設定管理を向上させるため、TOML形式の設定ファイルサポートを追加する。CLI引数、環境変数、設定ファイルの3層構造での設定管理を実現し、複雑な設定の再利用性と管理性を向上させる。

## Problem Statement
現在のParsentryは全ての設定をCLI引数または環境変数で指定する必要があり、以下の課題があります：

**設定管理の課題:**
- 複雑なプロジェクトでの設定の再利用困難
- チーム間での設定共有が手動作業
- CI/CDでの環境ごとの設定管理が煩雑
- 設定の可視性・バージョン管理が困難

**ユーザビリティの問題:**
- 長大なCLI引数による操作性低下
- 設定ミスによるエラーの頻発
- 新規ユーザーの学習コスト増大
- 環境変数の衝突リスク

**将来機能との統合課題:**
- LSP統合等の複雑な設定への対応困難
- プロジェクト固有設定の標準化不足
- 設定テンプレートの欠如

## Proposed Solution
TOML形式の設定ファイルサポートを実装し、以下の3層構造での設定管理を実現します：

### 1. 設定優先度（高 → 低）
1. **CLI引数** - 一時的なオーバーライド用
2. **環境変数** - システム/CI環境用
3. **設定ファイル** - プロジェクト標準設定用

### 2. 標準設定ファイル構造（parsentry.toml）
```toml
# === 基本設定 ===
[analysis]
model = "o4-mini"
min_confidence = 70
verbosity = 1
debug = false
language = "ja"

# === パス設定 ===
[paths]
output_dir = "reports"
root = "src"

# === フィルタリング設定 ===
[filtering]
vuln_types = ["sqli", "xss", "path_traversal"]
include_patterns = ["*.rs", "*.ts", "*.py"]
exclude_patterns = ["**/test/**", "**/node_modules/**"]

# === レポート設定 ===
[reporting]
formats = ["json", "sarif"]
generate_patterns = true
include_context = true

# === API設定 ===
[api]
base_url = "https://api.anthropic.com"
timeout_ms = 30000
retry_count = 3

# === パフォーマンス設定 ===
[performance]
max_file_size_kb = 50
parallel_analysis = true
cache_enabled = true

# === 将来拡張用（LSP統合準備） ===
[extensions]
# LSPサポート等の将来機能用セクション
enabled_features = ["tree_sitter"]
```

### 3. CLI統合設計
```bash
# 設定ファイル指定
parsentry --config parsentry.toml

# デフォルト設定ファイルの自動検索
# 検索順: ./parsentry.toml → ~/.config/parsentry/config.toml → /etc/parsentry/config.toml
parsentry --root src/

# 設定ファイル + CLI引数オーバーライド
parsentry --config parsentry.toml --model claude-3-5-sonnet --verbosity 2

# 設定ファイル生成ヘルパー
parsentry --generate-config > parsentry.toml
```

### 4. 設定管理システム実装
```rust
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct ParsentryConfig {
    #[serde(default)]
    pub analysis: AnalysisConfig,
    
    #[serde(default)]
    pub paths: PathsConfig,
    
    #[serde(default)]
    pub filtering: FilteringConfig,
    
    #[serde(default)]
    pub reporting: ReportingConfig,
    
    #[serde(default)]
    pub api: ApiConfig,
    
    #[serde(default)]
    pub performance: PerformanceConfig,
    
    #[serde(default)]
    pub extensions: ExtensionsConfig,
}

#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct AnalysisConfig {
    #[serde(default = "default_model")]
    pub model: String,
    
    #[serde(default = "default_min_confidence")]
    pub min_confidence: i32,
    
    #[serde(default)]
    pub verbosity: u8,
    
    #[serde(default)]
    pub debug: bool,
    
    #[serde(default = "default_language")]
    pub language: String,
}

impl ParsentryConfig {
    pub fn load_with_precedence(
        config_path: Option<PathBuf>,
        cli_args: &Args,
        env_vars: &HashMap<String, String>
    ) -> Result<Self> {
        // 1. ベース設定ファイル読み込み
        let mut config = if let Some(path) = config_path {
            Self::load_from_file(&path)?
        } else {
            Self::find_and_load_default()?
        };
        
        // 2. 環境変数でオーバーライド
        config.apply_env_vars(env_vars)?;
        
        // 3. CLI引数でオーバーライド
        config.apply_cli_args(cli_args)?;
        
        Ok(config)
    }
}
```

### 5. バリデーション・エラーハンドリング
```rust
impl ParsentryConfig {
    pub fn validate(&self) -> Result<(), ConfigError> {
        // パス存在確認
        if let Some(root) = &self.paths.root {
            if \!root.exists() {
                return Err(ConfigError::InvalidPath {
                    field: "paths.root".to_string(),
                    path: root.clone(),
                });
            }
        }
        
        // 値範囲確認
        if self.analysis.min_confidence < 0 || self.analysis.min_confidence > 100 {
            return Err(ConfigError::InvalidRange {
                field: "analysis.min_confidence".to_string(),
                value: self.analysis.min_confidence,
                valid_range: "0-100".to_string(),
            });
        }
        
        Ok(())
    }
}
```

### 1. プロジェクト標準設定の共有
```bash
# チーム標準設定をリポジトリにコミット
git add parsentry.toml
git commit -m "Add standard security analysis configuration"

# チームメンバーは設定ファイルを使用
parsentry  # 自動的にparsentry.tomlを検出・使用
```
**効果**: チーム間での設定統一、新規参加者のセットアップ簡素化

### 2. 環境別設定管理
```bash
# 開発環境用
parsentry --config config/dev.toml

# CI環境用
parsentry --config config/ci.toml --verbosity 0

# 本番環境用
parsentry --config config/prod.toml --min-confidence 90
```
**効果**: 環境特性に応じた最適な設定、運用ミスの削減

### 3. 設定テンプレートの提供
```bash
# プロジェクト種別ごとのテンプレート生成
parsentry --generate-config --template rust-project > rust-parsentry.toml
parsentry --generate-config --template web-app > webapp-parsentry.toml
parsentry --generate-config --template infrastructure > iac-parsentry.toml
```
**効果**: プロジェクト特性に応じた最適設定の迅速導入

### 4. CI/CD統合
```yaml
# GitHub Actions example
- name: Security Analysis
  run: parsentry --config .github/parsentry-ci.toml
  env:
    PARSENTRY_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
```
**効果**: CI/CD環境での設定管理簡素化、秘密情報の安全な分離

### 5. 段階的機能有効化
```toml
# parsentry.toml - 将来のLSP機能準備
[extensions]
enabled_features = ["tree_sitter"]  # 現在

# 将来的に
enabled_features = ["tree_sitter", "lsp_hybrid"]
```
**効果**: 新機能の段階的導入、下位互換性維持

## Feature Type
CLI enhancement

## Priority
High - Critical for adoption

### Design Subtasks
- [ ] **設定スキーマ設計**: TOML構造、デフォルト値、バリデーションルール設計
- [ ] **優先度システム設計**: CLI引数 > 環境変数 > 設定ファイルの適用ロジック
- [ ] **設定検索パス設計**: デフォルト設定ファイルの検索順序とパス定義
- [ ] **エラーハンドリング設計**: 設定エラーの分類とユーザーフレンドリーなメッセージ
- [ ] **拡張性設計**: 将来機能（LSP等）向けの設定セクション構造

### Implementation Subtasks
- [ ] **TOMLパーサー実装**: `serde`と`toml`クレートを使用した設定ファイル読み込み
- [ ] **設定マージ実装**: CLI引数、環境変数、設定ファイルの3層マージロジック
- [ ] **バリデーション実装**: 設定値の妥当性検証とエラー報告システム
- [ ] **CLI引数拡張**: `--config`オプション、`--generate-config`機能の追加
- [ ] **デフォルト検索実装**: 設定ファイルの自動検出機能
- [ ] **環境変数マッピング**: `PARSENTRY_*`環境変数の設定ファイル項目への自動マッピング

### Documentation Subtasks
- [ ] **設定ファイルリファレンス**: 全設定項目の詳細説明とサンプル
- [ ] **移行ガイド**: CLI引数から設定ファイルへの移行手順
- [ ] **ベストプラクティス**: プロジェクト種別ごとの推奨設定パターン
- [ ] **トラブルシューティング**: 設定関連の一般的な問題と解決策
- [ ] **テンプレート集**: 各種プロジェクトタイプ向け設定テンプレート

### Validation Subtasks
- [ ] **単体テスト**: 設定パーサー、マージロジック、バリデーション機能のテスト
- [ ] **統合テスト**: CLI引数・環境変数・設定ファイルの組み合わせテスト
- [ ] **エラーケーステスト**: 不正な設定ファイル、存在しないパス等のエラーハンドリング
- [ ] **下位互換性テスト**: 既存CLI引数のみでの動作継続確認
- [ ] **パフォーマンステスト**: 設定ファイル読み込みのオーバーヘッド測定
- [ ] **実環境テスト**: 各種プロジェクトでの設定ファイル使用検証

### 1. JSON設定ファイル
**メリット**: パース速度、JavaScript生態系との親和性
**デメリット**: コメント不可、人間の読み書きが困難、型安全性不足
**判断**: 設定ファイルの可読性・保守性を重視してTOMLを選択

### 2. YAML設定ファイル
**メリット**: 人間の可読性、階層構造の表現力
**デメリト**: インデント依存の構文エラーリスク、パース速度
**判断**: Rustエコシステム標準のTOMLがより安全で高速

### 3. 独自形式設定ファイル
**メリット**: 完全なカスタマイズ性、ドメイン特化最適化
**デメリット**: 学習コスト、エディタサポート不足、保守負荷
**判断**: 標準的なTOMLが開発効率・ユーザビリティで優位

### 技術実装詳細

**設定ファイル検索アルゴリズム:**
```rust
impl ParsentryConfig {
    fn find_default_config() -> Option<PathBuf> {
        let search_paths = vec\![
            "./parsentry.toml",                              // カレントディレクトリ
            "~/.config/parsentry/config.toml",              // ユーザー設定
            "/etc/parsentry/config.toml",                   // システム設定
        ];
        
        for path in search_paths {
            if Path::new(&path).exists() {
                return Some(PathBuf::from(path));
            }
        }
        None
    }
}
```

**環境変数マッピング:**
```rust
// PARSENTRY_ANALYSIS_MODEL → analysis.model
// PARSENTRY_PATHS_ROOT → paths.root
// PARSENTRY_API_BASE_URL → api.base_url

fn map_env_var_to_config_path(env_key: &str) -> Option<String> {
    if let Some(suffix) = env_key.strip_prefix("PARSENTRY_") {
        let config_path = suffix.to_lowercase().replace('_', ".");
        Some(config_path)
    } else {
        None
    }
}
```

**バリデーション詳細:**
```rust
#[derive(thiserror::Error, Debug)]
pub enum ConfigError {
    #[error("Invalid path in {field}: {path} does not exist")]
    InvalidPath { field: String, path: PathBuf },
    
    #[error("Invalid range in {field}: {value} (valid range: {valid_range})")]
    InvalidRange { field: String, value: i32, valid_range: String },
    
    #[error("Invalid model in {field}: {model} (available: {available:?})")]
    InvalidModel { field: String, model: String, available: Vec<String> },
    
    #[error("TOML parsing error: {0}")]
    TomlError(#[from] toml::de::Error),
}
```

### 将来機能との統合準備

**LSP設定セクション（将来用）:**
```toml
[extensions.lsp]
enabled = false  # デフォルトはfalse、明示的有効化が必要

[extensions.lsp.servers]
rust-analyzer = "/usr/bin/rust-analyzer"
typescript-language-server = "/usr/bin/typescript-language-server"
pylsp = "/usr/bin/pylsp"

[extensions.lsp.settings]
timeout_ms = 5000
fallback_to_tree_sitter = true
```

**コールグラフ設定セクション（将来用）:**
```toml
[extensions.call_graph]
enabled = false
output_formats = ["dot", "json"]
max_depth = 10
include_external_libs = false
```

### 移行戦略

**段階的導入計画:**
1. **フェーズ1**: 基本TOML設定サポート（現在のCLI引数をすべて設定ファイル化）
2. **フェーズ2**: 高度な設定機能（テンプレート、バリデーション強化）
3. **フェーズ3**: 拡張機能統合（LSP、コールグラフ等の設定基盤）

**下位互換性保証:**
- 既存CLI引数は完全に維持
- 設定ファイルなしでの動作は従来通り
- 段階的な設定ファイル導入が可能

この設定ファイル機能により、Parsentryは企業環境での採用に必要な設定管理能力を獲得し、将来の機能拡張（LSP統合、コールグラフ等）の基盤を構築できます。
